# Generated by Django 4.2.23 on 2025-07-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadtalker_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationrequest',
            name='cloned_voice_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
